### ISSUE TITLE
Java-docker JobProxy

### ISSUE THREAD

**Issue by pbelmann** [BiBiServ/jobproxy#29]
We should implement [java-docker](https://github.com/docker-java/docker-java) jobproxy.

**Comment by jkrue** [comment]
Instead of having a JobProxyJavaDocker and something like a JobProxyLocal framework we should integrate both functionalities in one framework.
1. JavaDocker for a task with container content 
2. Local execution for a task without container content
The other frameworks (Chronos, DRMAA) provides an equivalent  behaviour.

@pbelmann What do you think ?

**Comment by pbelmann** [comment]
Yes that is a good idea. This would help to implement more parts of the interface. I will create an new issue feature and schedule it for the new release.
